# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(choices=[(0, 'QB'), (1, 'RB'), (2, 'WR'), (3, 'K'), (4, 'TE')], max_length=10)),
                ('playedId', models.CharField(max_length=150)),
                ('starting', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=150)),
                ('team_owner', models.CharField(max_length=150)),
                ('avatarUrl', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='league.Team'),
        ),
    ]
