# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='avatarUrl',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
