# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20171219_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='playedId',
            new_name='player_Id',
        ),
    ]
