# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_auto_20171219_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='league_id',
            field=models.CharField(default='asdfsf', max_length=50),
            preserve_default=False,
        ),
    ]
