# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_auto_20171220_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=50)),
                ('league_id', models.CharField(max_length=150)),
            ],
        ),
    ]
